let liveTournamentTeams = [
  {
    "id": "t-1",
    "name": "ForgtN SoulZ",
    "logo": "or.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 42,
    "cqbKills": 18,
    "lrbKills": 14,
    "assists": 15,
    "cqbDmg": 2480,
    "lrbDmg": 1890
  },
  {
    "id": "t-2",
    "name": "RAKUZAN",
    "logo": "rakuzan.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 40,
    "cqbKills": 18,
    "lrbKills": 14,
    "assists": 15,
    "cqbDmg": 2365,
    "lrbDmg": 1795
  },
  {
    "id": "t-3",
    "name": "DRS",
    "logo": "unknown.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 38,
    "cqbKills": 17,
    "lrbKills": 13,
    "assists": 14,
    "cqbDmg": 2250,
    "lrbDmg": 1700
  },
  {
    "id": "t-4",
    "name": "BROCODZ",
    "logo": "unknown.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 36,
    "cqbKills": 16,
    "lrbKills": 13,
    "assists": 14,
    "cqbDmg": 2135,
    "lrbDmg": 1605
  },
  {
    "id": "t-5",
    "name": "TPA",
    "logo": "tpa.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 34,
    "cqbKills": 16,
    "lrbKills": 12,
    "assists": 13,
    "cqbDmg": 2020,
    "lrbDmg": 1510
  },
  {
    "id": "t-6",
    "name": "NIG",
    "logo": "night.png",
    "group": "B_VS_C",
    "match": 6,
    "placementPts": 32,
    "cqbKills": 15,
    "lrbKills": 12,
    "assists": 13,
    "cqbDmg": 1905,
    "lrbDmg": 1415
  },
  {
    "id": "t-7",
    "name": "MALAYALEES YODHA",
    "logo": "unknown.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 30,
    "cqbKills": 14,
    "lrbKills": 11,
    "assists": 12,
    "cqbDmg": 1790,
    "lrbDmg": 1320
  },
  {
    "id": "t-8",
    "name": "RDB",
    "logo": "RDB.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 28,
    "cqbKills": 14,
    "lrbKills": 11,
    "assists": 12,
    "cqbDmg": 1675,
    "lrbDmg": 1225
  },
  {
    "id": "t-9",
    "name": "TGA",
    "logo": "tga.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 26,
    "cqbKills": 13,
    "lrbKills": 10,
    "assists": 11,
    "cqbDmg": 1560,
    "lrbDmg": 1130
  },
  {
    "id": "t-10",
    "name": "NEXUS Esports",
    "logo": "or.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 24,
    "cqbKills": 12,
    "lrbKills": 10,
    "assists": 11,
    "cqbDmg": 1445,
    "lrbDmg": 1035
  },
  {
    "id": "t-11",
    "name": "HASHONE ESPORTS",
    "logo": "or.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 22,
    "cqbKills": 11,
    "lrbKills": 9,
    "assists": 10,
    "cqbDmg": 1330,
    "lrbDmg": 940
  },
  {
    "id": "t-12",
    "name": "SCORP",
    "logo": "or.png",
    "group": "B_VS_C",
    "match": 6,
    "placementPts": 20,
    "cqbKills": 11,
    "lrbKills": 9,
    "assists": 10,
    "cqbDmg": 1215,
    "lrbDmg": 845
  },
  {
    "id": "t-13",
    "name": "Maradu",
    "logo": "unknown.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 18,
    "cqbKills": 10,
    "lrbKills": 8,
    "assists": 9,
    "cqbDmg": 1100,
    "lrbDmg": 750
  },
  {
    "id": "t-14",
    "name": "Zodiac 30",
    "logo": "unknown.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 16,
    "cqbKills": 9,
    "lrbKills": 8,
    "assists": 9,
    "cqbDmg": 985,
    "lrbDmg": 655
  },
  {
    "id": "t-15",
    "name": "CITY TIGERS X",
    "logo": "unknown.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 14,
    "cqbKills": 9,
    "lrbKills": 7,
    "assists": 8,
    "cqbDmg": 870,
    "lrbDmg": 560
  },
  {
    "id": "t-16",
    "name": "UE  RED",
    "logo": "UE.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 12,
    "cqbKills": 8,
    "lrbKills": 7,
    "assists": 8,
    "cqbDmg": 755,
    "lrbDmg": 465
  },
  {
    "id": "t-17",
    "name": "ORK Esports",
    "logo": "or.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 20,
    "cqbKills": 8,
    "lrbKills": 6,
    "assists": 7,
    "cqbDmg": 1100,
    "lrbDmg": 850
  },
  {
    "id": "t-18",
    "name": "Kadayadi Boys",
    "logo": "unknown.png",
    "group": "B_VS_C",
    "match": 6,
    "placementPts": 19,
    "cqbKills": 8,
    "lrbKills": 6,
    "assists": 7,
    "cqbDmg": 1075,
    "lrbDmg": 830
  },
  {
    "id": "t-19",
    "name": "TEAM OBEY",
    "logo": "obey.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 18,
    "cqbKills": 8,
    "lrbKills": 6,
    "assists": 7,
    "cqbDmg": 1050,
    "lrbDmg": 810
  },
  {
    "id": "t-20",
    "name": "Andheri",
    "logo": "unknown.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 17,
    "cqbKills": 8,
    "lrbKills": 6,
    "assists": 7,
    "cqbDmg": 1025,
    "lrbDmg": 790
  },
  {
    "id": "t-21",
    "name": "K51 Officals",
    "logo": "k51.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 16,
    "cqbKills": 8,
    "lrbKills": 6,
    "assists": 7,
    "cqbDmg": 1000,
    "lrbDmg": 770
  },
  {
    "id": "t-22",
    "name": "Zero Hour",
    "logo": "ZE.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 15,
    "cqbKills": 7,
    "lrbKills": 6,
    "assists": 7,
    "cqbDmg": 975,
    "lrbDmg": 750
  },
  {
    "id": "t-23",
    "name": "TOP 1",
    "logo": "top1.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 14,
    "cqbKills": 7,
    "lrbKills": 6,
    "assists": 7,
    "cqbDmg": 950,
    "lrbDmg": 730
  },
  {
    "id": "t-24",
    "name": "Skill Issue",
    "logo": "UE.png",
    "group": "B_VS_C",
    "match": 6,
    "placementPts": 13,
    "cqbKills": 7,
    "lrbKills": 5,
    "assists": 6,
    "cqbDmg": 925,
    "lrbDmg": 710
  },
  {
    "id": "t-25",
    "name": "TKN",
    "logo": "unknown.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 12,
    "cqbKills": 7,
    "lrbKills": 5,
    "assists": 6,
    "cqbDmg": 900,
    "lrbDmg": 690
  },
  {
    "id": "t-26",
    "name": "RIFLE CLUB",
    "logo": "rifl.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 11,
    "cqbKills": 7,
    "lrbKills": 5,
    "assists": 6,
    "cqbDmg": 875,
    "lrbDmg": 670
  },
  {
    "id": "t-27",
    "name": "Indus Prime",
    "logo": "unknown.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 10,
    "cqbKills": 6,
    "lrbKills": 5,
    "assists": 6,
    "cqbDmg": 850,
    "lrbDmg": 650
  },
  {
    "id": "t-28",
    "name": "BadBoyz",
    "logo": "bad.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 9,
    "cqbKills": 6,
    "lrbKills": 5,
    "assists": 6,
    "cqbDmg": 825,
    "lrbDmg": 630
  },
  {
    "id": "t-29",
    "name": "WAX7",
    "logo": "unknown.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 8,
    "cqbKills": 6,
    "lrbKills": 5,
    "assists": 6,
    "cqbDmg": 800,
    "lrbDmg": 610
  },
  {
    "id": "t-30",
    "name": "CVA",
    "logo": "cvaa.png",
    "group": "B_VS_C",
    "match": 6,
    "placementPts": 7,
    "cqbKills": 6,
    "lrbKills": 5,
    "assists": 6,
    "cqbDmg": 775,
    "lrbDmg": 590
  },
  {
    "id": "t-31",
    "name": "BERSERK",
    "logo": "unknown.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 6,
    "cqbKills": 6,
    "lrbKills": 4,
    "assists": 5,
    "cqbDmg": 750,
    "lrbDmg": 570
  },
  {
    "id": "t-32",
    "name": "VNV",
    "logo": "unknown.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 5,
    "cqbKills": 5,
    "lrbKills": 4,
    "assists": 5,
    "cqbDmg": 725,
    "lrbDmg": 550
  },
  {
    "id": "t-33",
    "name": "XSTREAM THARAVAD",
    "logo": "unknown.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 4,
    "cqbKills": 5,
    "lrbKills": 4,
    "assists": 5,
    "cqbDmg": 700,
    "lrbDmg": 530
  },
  {
    "id": "t-34",
    "name": "KORTEX",
    "logo": "kortex.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 3,
    "cqbKills": 5,
    "lrbKills": 4,
    "assists": 5,
    "cqbDmg": 675,
    "lrbDmg": 510
  },
  {
    "id": "t-35",
    "name": "REV ME BRO",
    "logo": "revmebro.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 2,
    "cqbKills": 5,
    "lrbKills": 4,
    "assists": 5,
    "cqbDmg": 650,
    "lrbDmg": 490
  },
  {
    "id": "t-36",
    "name": "SOULS",
    "logo": "soul.png",
    "group": "B_VS_C",
    "match": 6,
    "placementPts": 1,
    "cqbKills": 5,
    "lrbKills": 4,
    "assists": 5,
    "cqbDmg": 625,
    "lrbDmg": 470
  },
  {
    "id": "t-37",
    "name": "Brawlers Hood (BRH)",
    "logo": "brh.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 0,
    "cqbKills": 4,
    "lrbKills": 3,
    "assists": 4,
    "cqbDmg": 600,
    "lrbDmg": 450
  },
  {
    "id": "t-38",
    "name": "KANDAM BROTHERS",
    "logo": "unknown.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 0,
    "cqbKills": 4,
    "lrbKills": 3,
    "assists": 4,
    "cqbDmg": 575,
    "lrbDmg": 430
  },
  {
    "id": "t-39",
    "name": "LVLX",
    "logo": "unknown.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 0,
    "cqbKills": 4,
    "lrbKills": 3,
    "assists": 4,
    "cqbDmg": 550,
    "lrbDmg": 410
  },
  {
    "id": "t-40",
    "name": "8XR ESP",
    "logo": "unknown.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 0,
    "cqbKills": 4,
    "lrbKills": 3,
    "assists": 4,
    "cqbDmg": 525,
    "lrbDmg": 390
  },
  {
    "id": "t-41",
    "name": "T-GANG",
    "logo": "tga.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 0,
    "cqbKills": 4,
    "lrbKills": 3,
    "assists": 4,
    "cqbDmg": 500,
    "lrbDmg": 370
  },
  {
    "id": "t-42",
    "name": "DICTATORS",
    "logo": "or.png",
    "group": "B_VS_C",
    "match": 6,
    "placementPts": 0,
    "cqbKills": 3,
    "lrbKills": 3,
    "assists": 4,
    "cqbDmg": 475,
    "lrbDmg": 350
  },
  {
    "id": "t-43",
    "name": "VENIN",
    "logo": "unknown.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 0,
    "cqbKills": 3,
    "lrbKills": 3,
    "assists": 4,
    "cqbDmg": 450,
    "lrbDmg": 330
  },
  {
    "id": "t-44",
    "name": "SVA",
    "logo": "unknown.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 0,
    "cqbKills": 3,
    "lrbKills": 2,
    "assists": 3,
    "cqbDmg": 425,
    "lrbDmg": 310
  },
  {
    "id": "t-45",
    "name": "KIDILOSKI",
    "logo": "kidi.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 0,
    "cqbKills": 3,
    "lrbKills": 2,
    "assists": 3,
    "cqbDmg": 400,
    "lrbDmg": 290
  },
  {
    "id": "t-46",
    "name": "LEGION OF STRIKERS",
    "logo": "unknown.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 0,
    "cqbKills": 3,
    "lrbKills": 2,
    "assists": 3,
    "cqbDmg": 375,
    "lrbDmg": 270
  },
  {
    "id": "t-47",
    "name": "Team Minus",
    "logo": "teamminus.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 0,
    "cqbKills": 2,
    "lrbKills": 2,
    "assists": 3,
    "cqbDmg": 350,
    "lrbDmg": 250
  },
  {
    "id": "t-48",
    "name": "TEAM BMG",
    "logo": "bmg.png",
    "group": "B_VS_C",
    "match": 6,
    "placementPts": 0,
    "cqbKills": 2,
    "lrbKills": 2,
    "assists": 3,
    "cqbDmg": 325,
    "lrbDmg": 230
  },
  {
    "id": "t-49",
    "name": "AIM X",
    "logo": "unknown.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 0,
    "cqbKills": 2,
    "lrbKills": 2,
    "assists": 3,
    "cqbDmg": 300,
    "lrbDmg": 210
  },
  {
    "id": "t-50",
    "name": "Ageing But Fearless",
    "logo": "unknown.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 0,
    "cqbKills": 2,
    "lrbKills": 2,
    "assists": 3,
    "cqbDmg": 275,
    "lrbDmg": 190
  },
  {
    "id": "t-51",
    "name": "TRINATH",
    "logo": "trinath.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 0,
    "cqbKills": 2,
    "lrbKills": 1,
    "assists": 2,
    "cqbDmg": 250,
    "lrbDmg": 170
  },
  {
    "id": "t-52",
    "name": "Team Alto",
    "logo": "alto.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 0,
    "cqbKills": 1,
    "lrbKills": 1,
    "assists": 2,
    "cqbDmg": 225,
    "lrbDmg": 150
  },
  {
    "id": "t-53",
    "name": "JUNGLI SENA",
    "logo": "sena.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 0,
    "cqbKills": 1,
    "lrbKills": 1,
    "assists": 2,
    "cqbDmg": 200,
    "lrbDmg": 130
  },
  {
    "id": "t-54",
    "name": "HELLFIRE",
    "logo": "unknown.png",
    "group": "B_VS_C",
    "match": 6,
    "placementPts": 0,
    "cqbKills": 1,
    "lrbKills": 1,
    "assists": 2,
    "cqbDmg": 175,
    "lrbDmg": 110
  },
  {
    "id": "t-55",
    "name": "The Reflex Matrix",
    "logo": "thereflexmatrix.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 0,
    "cqbKills": 1,
    "lrbKills": 1,
    "assists": 2,
    "cqbDmg": 150,
    "lrbDmg": 90
  },
  {
    "id": "t-56",
    "name": "CJ_Gaming_Arena",
    "logo": "cjgaming.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 0,
    "cqbKills": 1,
    "lrbKills": 1,
    "assists": 2,
    "cqbDmg": 125,
    "lrbDmg": 70
  },
  {
    "id": "t-57",
    "name": "MUTANT",
    "logo": "mutant.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 1,
    "cqbDmg": 100,
    "lrbDmg": 50
  },
  {
    "id": "t-58",
    "name": "MALAYALEES KARNA",
    "logo": "unknown.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 1,
    "cqbDmg": 75,
    "lrbDmg": 30
  },
  {
    "id": "t-59",
    "name": "Hashone Neo",
    "logo": "unknown.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 1,
    "cqbDmg": 50,
    "lrbDmg": 10
  },
  {
    "id": "t-60",
    "name": "Warlord X",
    "logo": "warlord.png",
    "group": "B_VS_C",
    "match": 6,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 1,
    "cqbDmg": 25,
    "lrbDmg": 0
  },
  {
    "id": "t-61",
    "name": "Squad One",
    "logo": "squadone.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 1,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-62",
    "name": "FATE",
    "logo": "fate.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 1,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-63",
    "name": "fRag Republic",
    "logo": "frag.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 1,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-64",
    "name": "M5 GAMING",
    "logo": "m5.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-65",
    "name": "OUTSTRIPPERS",
    "logo": "outstrippers.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-66",
    "name": "SQUAD MATRIX",
    "logo": "squadmatrix.png",
    "group": "B_VS_C",
    "match": 6,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-67",
    "name": "Plants Army",
    "logo": "plants.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-68",
    "name": "Rising Dragons",
    "logo": "rising.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-69",
    "name": "PDX",
    "logo": "pdx.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-70",
    "name": "Night Hunter",
    "logo": "night.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-71",
    "name": "UNKRITHI",
    "logo": "un.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-72",
    "name": "STUDS",
    "logo": "studs.png",
    "group": "B_VS_C",
    "match": 6,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-73",
    "name": "MARATHABAAD",
    "logo": "marathabaad.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-74",
    "name": "HAVK",
    "logo": "havk.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-75",
    "name": "RACR",
    "logo": "racr.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-76",
    "name": "Xtreme DOMINATORS",
    "logo": "or.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-77",
    "name": "Koya_IYKYK",
    "logo": "koya_iykyk.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-78",
    "name": "SAPPUNNIZ",
    "logo": "un.png",
    "group": "B_VS_C",
    "match": 6,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-79",
    "name": "Team FragFusion",
    "logo": "teamfragfusion.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-80",
    "name": "MALAYALEES VAJRA",
    "logo": "unknown.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-81",
    "name": "Rat Hunters",
    "logo": "un.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-82",
    "name": "High Fury",
    "logo": "hi.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-83",
    "name": "MEN IN BLACK",
    "logo": "unknown.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-84",
    "name": "TeamMindSpark",
    "logo": "mindspark.png",
    "group": "B_VS_C",
    "match": 6,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-85",
    "name": "DNA",
    "logo": "unknown.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-86",
    "name": "X-RAY",
    "logo": "X-RAY.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-87",
    "name": "TEAM DIVISION",
    "logo": "unknown.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-88",
    "name": "Team XD",
    "logo": "teamxd.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-89",
    "name": "Fourged Titans",
    "logo": "fourged.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-90",
    "name": "Rizzlers",
    "logo": "unknown.png",
    "group": "B_VS_C",
    "match": 6,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-91",
    "name": "Zero Trace",
    "logo": "ZE.png",
    "group": "A_VS_B",
    "match": 1,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-92",
    "name": "THE UNKNOWN",
    "logo": "unknown.png",
    "group": "C_VS_D",
    "match": 2,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-93",
    "name": "Ocean Gaming",
    "logo": "oceangaming.png",
    "group": "A_VS_C",
    "match": 3,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-94",
    "name": "P9-Pulse9",
    "logo": "p9.png",
    "group": "B_VS_D",
    "match": 4,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  },
  {
    "id": "t-95",
    "name": "4 Guys",
    "logo": "4guys.png",
    "group": "A_VS_D",
    "match": 5,
    "placementPts": 0,
    "cqbKills": 0,
    "lrbKills": 0,
    "assists": 0,
    "cqbDmg": 0,
    "lrbDmg": 0
  }
];